import { assets, ownedAssets } from "@/types";

export const topsAssets: assets[] = [
    {
        img: 'btc.svg',
        code: 'BTC',
        change: '-2.5%',
        name: 'Bitcoin',
        rate: '26,481.48',
    },
    {
        img: 'eth.svg',
        code: 'ETH',
        change: '2.5%',
        name: 'Ethereum',
        rate: '26,481.48',
    },
    {
        img: 'usdt.svg',
        code: 'USDT',
        change: '-2.5%',
        name: 'Tether',
        rate: '26,481.48',
    },
    {
        img: 'tron.webp',
        code: 'TRX',
        change: '2.5%',
        name: 'Tron',
        rate: '26,481.48',
    },
    {
        img: 'AAVE.webp',
        code: 'AAVE',
        change: '-2.5%',
        name: 'Aave',
        rate: '26,481.48',
    },
    {
        img: 'avanlache.webp',
        code: 'AVAX',
        change: '2.5',
        name: 'Avanlanche',
        rate: '26,481.48',
    },
    {
        img: 'litecoin.webp',
        code: 'LTC',
        change: '2.5',
        name: 'Litecoin',
        rate: '26,481.48',
    },
    {
        img: 'polygon.webp',
        code: 'MATIC',
        change: '2.5',
        name: 'Polygon',
        rate: '26,481.48',
    },
    {
        img: 'shiba.webp',
        code: 'SHIB',
        change: '2.5',
        name: 'Shiba Inu',
        rate: '26,481.48',
    },
    {
        img: 'usdt.svg',
        code: 'USDT',
        change: '2.5',
        name: 'Tether',
        rate: '26,481.48',
    },
    {
        img: 'sol.webp',
        code: 'SOL',
        change: '2.5',
        name: 'Solana',
        rate: '26,481.48',
    },
    {
        img: 'eth.svg',
        code: 'ETH',
        change: '2.5',
        name: 'Ethereum',
        rate: '26,481.48',
    },
    {
        img: 'usdt.svg',
        code: 'USDT',
        change: '2.5',
        name: 'Tether',
        rate: '26,481.48',
    },
    {
        img: 'usdt.svg',
        code: 'USDT',
        change: '2.5',
        name: 'Tether',
        rate: '26,481.48',
    },
]

export const owned: ownedAssets[] = [
    {
        img: 'btc.svg',
        code: 'BTC',
        asset_value: '0.00023',
        name: 'Bitcoin',
        fiat_value: '20,000',
    },
    {
        img: 'eth.svg',
        code: 'ETH',
        asset_value: '0.00021',
        name: 'Ethereum',
        fiat_value: '20,000',
    },
    {
        img: 'usdt.svg',
        code: 'USDT',
        asset_value: '0.00021',
        name: 'Tether',
        fiat_value: '5,000',
    },
    {
        img: 'binance.svg',
        code: 'BNB',
        asset_value: '0.00021',
        name: 'Binance',
        fiat_value: '5,000',
    },
    {
        img: 'doge-coin.svg',
        code: 'DOGE',
        asset_value: '0.00021',
        name: 'Dogecoin',
        fiat_value: '0.000',
    },
    {
        img: 'tezos.svg',
        code: 'TEZ',
        asset_value: '0.00021',
        name: 'Tezos',
        fiat_value: '0.000',
    },
    {
        img: 'AAVE.webp',
        code: 'AAVE',
        asset_value: '0.00023',
        name: 'Aave',
        fiat_value: '20,000',
    },
    {
        img: 'tron.webp',
        code: 'TRX',
        asset_value: '0.00023',
        name: 'Tron',
        fiat_value: '20,000',
    },
    {
        img: 'shiba.webp',
        code: 'SHIB',
        asset_value: '0.00023',
        name: 'Shiba Inu',
        fiat_value: '20,000',
    },
    {
        img: 'sol.webp',
        code: 'SOL',
        asset_value: '0.00023',
        name: 'Solana',
        fiat_value: '20,000',
    },
    {
        img: 'litecoin.webp',
        code: 'LTC',
        asset_value: '0.00021',
        name: 'Litecoin',
        fiat_value: '0.000',
    },
    {
        img: 'avanlache.webp',
        code: 'AVAX',
        asset_value: '0.00021',
        name: 'Avalanche',
        fiat_value: '0.000',
    },
]
