import { assets, ownedAssets } from "@/types";

export const topsAssets: assets[] = [
    {
        img: 'btc.svg',
        code: 'BTC',
        change: '2.5%',
        name: 'Bitcoin',
        rate: '26,481.48',
    },
    {
        img: 'eth.svg',
        code: 'ETH',
        change: '2.5%',
        name: 'Ethereum',
        rate: '26,481.48',
    },
    {
        img: 'usdt.svg',
        code: 'USDT',
        change: '2.5%',
        name: 'Tether',
        rate: '26,481.48',
    },
    {
        img: 'usdt.svg',
        code: 'USDT',
        change: '2.5%',
        name: 'Tether',
        rate: '26,481.48',
    },
    {
        img: 'usdt.svg',
        code: 'USDT',
        change: '2.5%',
        name: 'Tether',
        rate: '26,481.48',
    },
    {
        img: 'usdt.svg',
        code: 'USDT',
        change: '2.5',
        name: 'Tether',
        rate: '26,481.48',
    },
    {
        img: 'usdt.svg',
        code: 'USDT',
        change: '2.5',
        name: 'Tether',
        rate: '26,481.48',
    },
    {
        img: 'usdt.svg',
        code: 'USDT',
        change: '2.5',
        name: 'Tether',
        rate: '26,481.48',
    },
    {
        img: 'eth.svg',
        code: 'ETH',
        change: '2.5',
        name: 'Ethereum',
        rate: '26,481.48',
    },
    {
        img: 'usdt.svg',
        code: 'USDT',
        change: '2.5',
        name: 'Tether',
        rate: '26,481.48',
    },
    {
        img: 'usdt.svg',
        code: 'USDT',
        change: '2.5',
        name: 'Tether',
        rate: '26,481.48',
    },
    {
        img: 'eth.svg',
        code: 'ETH',
        change: '2.5',
        name: 'Ethereum',
        rate: '26,481.48',
    },
    {
        img: 'usdt.svg',
        code: 'USDT',
        change: '2.5',
        name: 'Tether',
        rate: '26,481.48',
    },
    {
        img: 'usdt.svg',
        code: 'USDT',
        change: '2.5',
        name: 'Tether',
        rate: '26,481.48',
    },
]

export const owned: ownedAssets[] = [
    {
        img: 'btc.svg',
        code: 'BTC',
        asset_value: '0.00023',
        name: 'Bitcoin',
        fiat_value: '20,000',
    },
    {
        img: 'eth.svg',
        code: 'ETH',
        asset_value: '0.00021',
        name: 'Ethereum',
        fiat_value: '20,000',
    },
    {
        img: 'usdt.svg',
        code: 'USDT',
        asset_value: '0.00021',
        name: 'Tether',
        fiat_value: '5,000',
    },
    {
        img: 'binance.svg',
        code: 'BNB',
        asset_value: '0.00021',
        name: 'Binance',
        fiat_value: '5,000',
    },
    {
        img: 'doge-coin.svg',
        code: 'DOGE',
        asset_value: '0.00021',
        name: 'Dogecoin',
        fiat_value: '0.000',
    },
    {
        img: 'tezos.svg',
        code: 'TEZ',
        asset_value: '0.00021',
        name: 'Tezos',
        fiat_value: '0.000',
    },
    {
        img: 'btc.svg',
        code: 'BTC',
        asset_value: '0.00023',
        name: 'Bitcoin',
        fiat_value: '20,000',
    },
    {
        img: 'btc.svg',
        code: 'BTC',
        asset_value: '0.00023',
        name: 'Bitcoin',
        fiat_value: '20,000',
    },
    {
        img: 'btc.svg',
        code: 'BTC',
        asset_value: '0.00023',
        name: 'Bitcoin',
        fiat_value: '20,000',
    },
    {
        img: 'btc.svg',
        code: 'BTC',
        asset_value: '0.00023',
        name: 'Bitcoin',
        fiat_value: '20,000',
    },
    {
        img: 'doge-coin.svg',
        code: 'DOGE',
        asset_value: '0.00021',
        name: 'Dogecoin',
        fiat_value: '0.000',
    },
    {
        img: 'tezos.svg',
        code: 'TEZ',
        asset_value: '0.00021',
        name: 'Tezos',
        fiat_value: '0.000',
    },
]
